services:
  backend-dev:
    build:
      context: ./backend
      target: dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/node_modules:/app/node_modules:ro
    network_mode: "host"
    stdin_open: true
    tty: true

  backend-prod:
    build:
      context: ./backend
      target: prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true

  frontend-home:
    build:
      context: ./frontend/
      target: home-dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/home/src:/app/src:ro
      - ./frontend/home/node_modules:/app/node_modules
    stdin_open: true
    tty: true

  frontend-home-prod:
    build:
      context: ./frontend/
      target: home-prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    stdin_open: true
    tty: true

  frontend-user:
    build:
      context: ./frontend/
      target: user-dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/user/src:/app/src:ro
      - ./frontend/user/node_modules:/app/node_modules
    stdin_open: true
    tty: true

  frontend-admin:
    build:
      context: ./frontend/
      target: admin-dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/admin/src:/app/src:ro
      - ./frontend/admin/node_modules:/app/node_modules
    stdin_open: true
    tty: true

  frontend-nginx-server:
    build:
      context: ./frontend/
      target: server
    ports:
      - 80:80
    stdin_open: true
    tty: true
