services:
  backend-dev:
    build:
      context: ./backend
      target: dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/node_modules:/app/node_modules:ro
    stdin_open: true
    tty: true

  backend-prod:
    build:
      context: ./backend
      target: prod
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true

  frontend-dev:
    build:
      context: ./frontend/
      target: dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
        - "FRONTEND=${FRONTEND:-home}"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/${FRONTEND:-home}/src:/app/src:ro
      - ./frontend/${FRONTEND:-home}/node_modules:/app/node_modules
    stdin_open: true
    tty: true
