<template>
  <div class="loadingio-spinner-eclipse-g4pl3vkiypi">
    <div class="ldio-0y50knxdjnl">
      <div></div>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
@keyframes ldio-0y50knxdjnl {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-0y50knxdjnl div {
  position: absolute;
  animation: ldio-0y50knxdjnl 1s linear infinite;
  height: 89%;
  aspect-ratio: 1/1;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #fcdcfd;
  transform-origin: 50% 50%;
}
.loadingio-spinner-eclipse-g4pl3vkiypi {
  height: 100%;
  aspect-ratio: 1/1;
  display: inline-block;
  overflow: hidden;
  position: absolute;
  z-index: 2;
}
.ldio-0y50knxdjnl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0y50knxdjnl div {
  box-sizing: content-box;
}

@media only screen and (max-width: 430px) {
  .ldio-0y50knxdjnl div {
    height: 86%;
  }
}
/* generated by https://loading.io/ */
</style>
