// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountType: typeof import('./src/components/AccountType.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    CoinMarketSkeleton: typeof import('./src/components/ui/CoinMarketSkeleton.vue')['default']
    ComponentLoader: typeof import('./src/components/ui/ComponentLoader.vue')['default']
    CryptoTable: typeof import('./src/components/widgets/CryptoTable.vue')['default']
    CryptoWidget: typeof import('./src/components/widgets/CryptoWidget.vue')['default']
    Curve: typeof import('./src/components/home/Curve.vue')['default']
    FloatingMenu: typeof import('./src/components/header/FloatingMenu.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoogleTranslate: typeof import('./src/components/widgets/GoogleTranslate.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Minning: typeof import('./src/components/home/Minning/Minning.vue')['default']
    MinningInfo: typeof import('./src/components/home/Minning/MinningInfo.vue')['default']
    MinningProgress: typeof import('./src/components/home/Minning/MinningProgress.vue')['default']
    MinningSpinner: typeof import('./src/components/home/Minning/MinningSpinner.vue')['default']
    ModalCancel: typeof import('./src/components/ui/modal/ModalCancel.vue')['default']
    ModalDanger: typeof import('./src/components/ui/modal/ModalDanger.vue')['default']
    ModalInfo: typeof import('./src/components/ui/modal/ModalInfo.vue')['default']
    ModalSuccess: typeof import('./src/components/ui/modal/ModalSuccess.vue')['default']
    ModalWarning: typeof import('./src/components/ui/modal/ModalWarning.vue')['default']
    MyCanvas: typeof import('./src/components/ui/MyCanvas.vue')['default']
    MyDataTable: typeof import('./src/components/ui/MyDataTable.vue')['default']
    MyModal: typeof import('./src/components/ui/MyModal.vue')['default']
    MyProgressBar: typeof import('./src/components/ui/MyProgressBar.vue')['default']
    MyQRCode: typeof import('./src/components/ui/MyQRCode.vue')['default']
    MySelect: typeof import('./src/components/ui/MySelect.vue')['default']
    NavHeader: typeof import('./src/components/header/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/header/NavItem.vue')['default']
    PackageInfo: typeof import('./src/components/home/PackageInfo.vue')['default']
    PaymentMethod: typeof import('./src/components/PaymentMethod.vue')['default']
    PlanCard: typeof import('./src/components/Cards/PlanCard.vue')['default']
    PostLoading: typeof import('./src/components/PostLoading.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    Sidebar: typeof import('./src/components/header/Sidebar.vue')['default']
    TestimonyCard: typeof import('./src/components/Cards/TestimonyCard.vue')['default']
    WhatsApp: typeof import('./src/components/widgets/WhatsApp.vue')['default']
  }
}
